"""add color and size column on items table

Revision ID: 08dbfd227b61
Revises: 7af306bc5d51
Create Date: 2025-03-25 13:11:14.183832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08dbfd227b61'
down_revision: Union[str, None] = '7af306bc5d51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('color', sa.String(), nullable=True))
    op.add_column('items', sa.Column('size', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'size')
    op.drop_column('items', 'color')
    # ### end Alembic commands ###
