"""Initial migration

Revision ID: 13fdeea5e547
Revises: 
Create Date: 2025-03-25 12:40:49.622030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13fdeea5e547'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('items')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('item_id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('description', sa.VARCHAR(length=60), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=True),
    sa.Column('upc', sa.FLOAT(), nullable=True),
    sa.Column('item_class', sa.VARCHAR(length=50), nullable=True),
    sa.Column('is_offer', sa.BOOLEAN(), nullable=True),
    sa.Column('default_cfg', sa.VARCHAR(length=10), nullable=True),
    sa.Column('custum1', sa.VARCHAR(length=30), nullable=True),
    sa.Column('custum2', sa.VARCHAR(length=30), nullable=True),
    sa.Column('custum3', sa.VARCHAR(length=30), nullable=True),
    sa.Column('custum4', sa.VARCHAR(length=30), nullable=True),
    sa.Column('custum5', sa.VARCHAR(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=True),
    sa.Column('password', sa.VARCHAR(length=50), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('max_logins', sa.FLOAT(), nullable=True),
    sa.Column('email_addr', sa.VARCHAR(), nullable=True),
    sa.Column('pall_cap', sa.VARCHAR(), nullable=True),
    sa.Column('comments', sa.VARCHAR(), nullable=True),
    sa.Column('role', sa.VARCHAR(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
