"""Updated ItemClass table changed column item class id

Revision ID: 143696549d71
Revises: fd7488785975
Create Date: 2025-03-26 13:18:39.005131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '143696549d71'
down_revision: Union[str, None] = 'fd7488785975'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_class', sa.Column('item_class_id', sa.String(), nullable=False))
    op.drop_column('item_class', 'item_class')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_class', sa.Column('item_class', sa.VARCHAR(), nullable=False))
    op.drop_column('item_class', 'item_class_id')
    # ### end Alembic commands ###
