"""updated item table added description2

Revision ID: 1aebeeabcfd7
Revises: a0d88e85f8cf
Create Date: 2025-03-26 12:11:01.146764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aebeeabcfd7'
down_revision: Union[str, None] = 'a0d88e85f8cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('description2', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'description2')
    # ### end Alembic commands ###
