"""Updated OrderTypes addes label Form

Revision ID: 5dc43e9d9613
Revises: 09ca2088edbc
Create Date: 2025-04-09 13:34:24.648381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dc43e9d9613'
down_revision: Union[str, None] = '09ca2088edbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_type', sa.Column('label_form', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_type', 'label_form')
    # ### end Alembic commands ###
