"""add Tax_id column on vendors

Revision ID: 636000923c0a
Revises: d391c00b6608
Create Date: 2025-04-07 14:03:38.936825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '636000923c0a'
down_revision: Union[str, None] = 'd391c00b6608'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('tax_id', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'tax_id')
    # ### end Alembic commands ###
