"""made changes on location_types table

Revision ID: 64b9b03001ad
Revises: cdebcb0c8faf
Create Date: 2025-03-27 15:52:43.503872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64b9b03001ad'
down_revision: Union[str, None] = 'cdebcb0c8faf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('scan_location', sa.String(), nullable=True))
    op.add_column('locations', sa.Column('black_hole_flag', sa.String(length=1), nullable=True))
    op.add_column('locations', sa.Column('proximiti_in', sa.String(), nullable=True))
    op.add_column('locations', sa.Column('proximiti_out', sa.String(), nullable=True))
    op.add_column('locations', sa.Column('has_assign_flag', sa.String(length=1), nullable=True))
    op.add_column('locations', sa.Column('has_contents_flag', sa.String(length=1), nullable=True))
    op.add_column('locations', sa.Column('has_pending_flag', sa.String(length=1), nullable=True))
    op.add_column('locations', sa.Column('putaway_class', sa.String(), nullable=True))
    op.add_column('locations', sa.Column('pick_class', sa.String(), nullable=True))
    op.add_column('locations', sa.Column('rstk_class', sa.String(), nullable=True))
    op.add_column('locations', sa.Column('blocked_code', sa.String(), nullable=True))
    op.add_column('locations', sa.Column('palle_cap', sa.Integer(), nullable=True))
    op.add_column('locations', sa.Column('carton_cap', sa.Integer(), nullable=True))
    op.add_column('locations', sa.Column('max_weight', sa.Integer(), nullable=True))
    op.add_column('locations', sa.Column('max_height', sa.Integer(), nullable=True))
    op.add_column('locations', sa.Column('max_width', sa.Integer(), nullable=True))
    op.add_column('locations', sa.Column('max_depth', sa.Integer(), nullable=True))
    op.add_column('locations', sa.Column('uom_max_weight', sa.String(), nullable=True))
    op.add_column('locations', sa.Column('uom_max_height', sa.String(), nullable=True))
    op.add_column('locations', sa.Column('uom_max_width', sa.String(), nullable=True))
    op.add_column('locations', sa.Column('uom_max_depth', sa.String(), nullable=True))
    op.add_column('locations', sa.Column('uom_carton_cap', sa.String(), nullable=True))
    op.add_column('locations', sa.Column('pallet_qty_act', sa.Integer(), nullable=True))
    op.add_column('locations', sa.Column('carton_qty_act', sa.Integer(), nullable=True))
    op.add_column('locations', sa.Column('aisle', sa.String(), nullable=True))
    op.add_column('locations', sa.Column('bay', sa.String(), nullable=True))
    op.add_column('locations', sa.Column('loc_level', sa.String(), nullable=True))
    op.add_column('locations', sa.Column('slot', sa.String(), nullable=True))
    op.add_column('locations', sa.Column('pnd_location_id1', sa.String(), nullable=True))
    op.add_column('locations', sa.Column('pnd_location_id2', sa.String(), nullable=True))
    op.add_column('locations', sa.Column('last_touch', sa.DateTime(), nullable=True))
    op.add_column('locations', sa.Column('last_touced_tm', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'last_touced_tm')
    op.drop_column('locations', 'last_touch')
    op.drop_column('locations', 'pnd_location_id2')
    op.drop_column('locations', 'pnd_location_id1')
    op.drop_column('locations', 'slot')
    op.drop_column('locations', 'loc_level')
    op.drop_column('locations', 'bay')
    op.drop_column('locations', 'aisle')
    op.drop_column('locations', 'carton_qty_act')
    op.drop_column('locations', 'pallet_qty_act')
    op.drop_column('locations', 'uom_carton_cap')
    op.drop_column('locations', 'uom_max_depth')
    op.drop_column('locations', 'uom_max_width')
    op.drop_column('locations', 'uom_max_height')
    op.drop_column('locations', 'uom_max_weight')
    op.drop_column('locations', 'max_depth')
    op.drop_column('locations', 'max_width')
    op.drop_column('locations', 'max_height')
    op.drop_column('locations', 'max_weight')
    op.drop_column('locations', 'carton_cap')
    op.drop_column('locations', 'palle_cap')
    op.drop_column('locations', 'blocked_code')
    op.drop_column('locations', 'rstk_class')
    op.drop_column('locations', 'pick_class')
    op.drop_column('locations', 'putaway_class')
    op.drop_column('locations', 'has_pending_flag')
    op.drop_column('locations', 'has_contents_flag')
    op.drop_column('locations', 'has_assign_flag')
    op.drop_column('locations', 'proximiti_out')
    op.drop_column('locations', 'proximiti_in')
    op.drop_column('locations', 'black_hole_flag')
    op.drop_column('locations', 'scan_location')
    # ### end Alembic commands ###
