"""add custom6 to items table

Revision ID: 7af306bc5d51
Revises: e9f0ba14ceca
Create Date: 2025-03-25 12:48:32.550884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7af306bc5d51'
down_revision: Union[str, None] = 'e9f0ba14ceca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('custum6', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'custum6')
    # ### end Alembic commands ###
