"""Update location table

Revision ID: 7d4a7293faef
Revises: 64b9b03001ad
Create Date: 2025-04-01 19:47:05.529751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d4a7293faef'
down_revision: Union[str, None] = '64b9b03001ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   # op.alter_column('locations', 'max_weight',
    #           existing_type=sa.INTEGER(),
     #          type_=sa.Float(),
      #         existing_nullable=True)
    #op.alter_column('locations', 'max_height',
   #            existing_type=sa.INTEGER(),
    #           type_=sa.Float(),
    #           existing_nullable=True)
    #op.alter_column('locations', 'max_width',
    #           existing_type=sa.INTEGER(),
     #          type_=sa.Float(),
     #          existing_nullable=True)
    #op.alter_column('locations', 'max_depth',
     #          existing_type=sa.INTEGER(),
     #          type_=sa.Float(),
     #          existing_nullable=True)
    #op.drop_column('locations', 'last_touced_tm')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('locations', sa.Column('last_touced_tm', sa.TIME(), nullable=True))
    #op.alter_column('locations', 'max_depth',
    #           existing_type=sa.Float(),
    #           type_=sa.INTEGER(),
    #           existing_nullable=True)
    #op.alter_column('locations', 'max_width',
    #           existing_type=sa.Float(),
    #           type_=sa.INTEGER(),
    #           existing_nullable=True)
    #op.alter_column('locations', 'max_height',
    #           existing_type=sa.Float(),
    #           type_=sa.INTEGER(),
    #           existing_nullable=True)
    #op.alter_column('locations', 'max_weight',
    #           existing_type=sa.Float(),
    ##           type_=sa.INTEGER(),
     #          existing_nullable=True)
    # ### end Alembic commands ###
