"""add color and size on items table

Revision ID: 838fdbcbe775
Revises: 49463867affc
Create Date: 2025-03-25 13:26:17.516458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '838fdbcbe775'
down_revision: Union[str, None] = '49463867affc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('color', sa.String(), nullable=True))
    op.add_column('items', sa.Column('size', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'size')
    op.drop_column('items', 'color')
    # ### end Alembic commands ###
