"""Update Purchase LInes2

Revision ID: 95eba1de0443
Revises: 19c35bc9c438
Create Date: 2025-04-15 14:36:17.507948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95eba1de0443'
down_revision: Union[str, None] = '19c35bc9c438'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('purchase_order_lines',
    sa.Column('total_pieces', sa.Float(), nullable=False, server_default="0")
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_order_lines', 'total_pieces')
    # ### end Alembic commands ###
