"""updated Items table

Revision ID: a0d88e85f8cf
Revises: 838fdbcbe775
Create Date: 2025-03-26 12:05:16.942305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0d88e85f8cf'
down_revision: Union[str, None] = '838fdbcbe775'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('alt_item_id1', sa.Integer(), nullable=True))
    op.add_column('items', sa.Column('alt_item_id2', sa.Integer(), nullable=True))
    op.add_column('items', sa.Column('brand', sa.String(length=30), nullable=True))
    op.add_column('items', sa.Column('style', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'style')
    op.drop_column('items', 'brand')
    op.drop_column('items', 'alt_item_id2')
    op.drop_column('items', 'alt_item_id1')
    # ### end Alembic commands ###
