"""UPdate PO model table

Revision ID: a48e8da24d87
Revises: 136c524eca5c
Create Date: 2025-04-14 16:39:39.937372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a48e8da24d87'
down_revision: Union[str, None] = '136c524eca5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('ship_company_name', sa.String(length=100), nullable=True))
    op.add_column('purchase_orders', sa.Column('ship_address', sa.String(length=150), nullable=True))
    op.add_column('purchase_orders', sa.Column('ship_city', sa.String(length=50), nullable=True))
    op.add_column('purchase_orders', sa.Column('ship_state', sa.String(length=50), nullable=True))
    op.add_column('purchase_orders', sa.Column('ship_zip_code', sa.String(length=20), nullable=True))
    op.add_column('purchase_orders', sa.Column('ship_country', sa.String(length=50), nullable=True))
    op.add_column('purchase_orders', sa.Column('ship_contact_name', sa.String(length=50), nullable=True))
    op.add_column('purchase_orders', sa.Column('ship_contact_phone', sa.String(length=30), nullable=True))
    op.add_column('purchase_orders', sa.Column('ship_tax_id', sa.String(length=30), nullable=True))
    op.add_column('purchase_orders', sa.Column('bill_company_name', sa.String(length=100), nullable=True))
    op.add_column('purchase_orders', sa.Column('bill_address', sa.String(length=150), nullable=True))
    op.add_column('purchase_orders', sa.Column('bill_city', sa.String(length=50), nullable=True))
    op.add_column('purchase_orders', sa.Column('bill_state', sa.String(length=50), nullable=True))
    op.add_column('purchase_orders', sa.Column('bill_zip_code', sa.String(length=20), nullable=True))
    op.add_column('purchase_orders', sa.Column('bill_country', sa.String(length=50), nullable=True))
    op.add_column('purchase_orders', sa.Column('bill_contact_name', sa.String(length=50), nullable=True))
    op.add_column('purchase_orders', sa.Column('bill_contact_phone', sa.String(length=30), nullable=True))
    op.add_column('purchase_orders', sa.Column('bill_tax_id', sa.String(length=30), nullable=True))
    op.add_column('purchase_orders', sa.Column('custom_1', sa.String(length=100), nullable=True))
    op.add_column('purchase_orders', sa.Column('custom_2', sa.String(length=100), nullable=True))
    op.add_column('purchase_orders', sa.Column('custom_3', sa.String(length=100), nullable=True))
    op.add_column('purchase_orders', sa.Column('custom_4', sa.String(length=100), nullable=True))
    op.add_column('purchase_orders', sa.Column('custom_5', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_orders', 'custom_5')
    op.drop_column('purchase_orders', 'custom_4')
    op.drop_column('purchase_orders', 'custom_3')
    op.drop_column('purchase_orders', 'custom_2')
    op.drop_column('purchase_orders', 'custom_1')
    op.drop_column('purchase_orders', 'bill_tax_id')
    op.drop_column('purchase_orders', 'bill_contact_phone')
    op.drop_column('purchase_orders', 'bill_contact_name')
    op.drop_column('purchase_orders', 'bill_country')
    op.drop_column('purchase_orders', 'bill_zip_code')
    op.drop_column('purchase_orders', 'bill_state')
    op.drop_column('purchase_orders', 'bill_city')
    op.drop_column('purchase_orders', 'bill_address')
    op.drop_column('purchase_orders', 'bill_company_name')
    op.drop_column('purchase_orders', 'ship_tax_id')
    op.drop_column('purchase_orders', 'ship_contact_phone')
    op.drop_column('purchase_orders', 'ship_contact_name')
    op.drop_column('purchase_orders', 'ship_country')
    op.drop_column('purchase_orders', 'ship_zip_code')
    op.drop_column('purchase_orders', 'ship_state')
    op.drop_column('purchase_orders', 'ship_city')
    op.drop_column('purchase_orders', 'ship_address')
    op.drop_column('purchase_orders', 'ship_company_name')
    op.alter_column('a_contents', 'item_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
