"""Recreate location table

Revision ID: a69c180930ef
Revises: 7d4a7293faef
Create Date: 2025-04-01 19:54:05.441634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a69c180930ef'
down_revision: Union[str, None] = '7d4a7293faef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('location_id', sa.String(), nullable=False),
    sa.Column('location_type', sa.String(), nullable=False),
    sa.Column('scan_location', sa.String(), nullable=True),
    sa.Column('black_hole_flag', sa.String(length=1), nullable=True),
    sa.Column('proximiti_in', sa.String(), nullable=True),
    sa.Column('proximiti_out', sa.String(), nullable=True),
    sa.Column('has_assign_flag', sa.String(length=1), nullable=True),
    sa.Column('has_contents_flag', sa.String(length=1), nullable=True),
    sa.Column('has_pending_flag', sa.String(length=1), nullable=True),
    sa.Column('putaway_class', sa.String(), nullable=True),
    sa.Column('pick_class', sa.String(), nullable=True),
    sa.Column('rstk_class', sa.String(), nullable=True),
    sa.Column('blocked_code', sa.String(), nullable=True),
    sa.Column('palle_cap', sa.Integer(), nullable=True),
    sa.Column('carton_cap', sa.Integer(), nullable=True),
    sa.Column('max_weight', sa.Float(), nullable=True),
    sa.Column('max_height', sa.Float(), nullable=True),
    sa.Column('max_width', sa.Float(), nullable=True),
    sa.Column('max_depth', sa.Float(), nullable=True),
    sa.Column('uom_max_weight', sa.String(), nullable=True),
    sa.Column('uom_max_height', sa.String(), nullable=True),
    sa.Column('uom_max_width', sa.String(), nullable=True),
    sa.Column('uom_max_depth', sa.String(), nullable=True),
    sa.Column('uom_carton_cap', sa.String(), nullable=True),
    sa.Column('pallet_qty_act', sa.Integer(), nullable=True),
    sa.Column('carton_qty_act', sa.Integer(), nullable=True),
    sa.Column('aisle', sa.String(), nullable=True),
    sa.Column('bay', sa.String(), nullable=True),
    sa.Column('loc_level', sa.String(), nullable=True),
    sa.Column('slot', sa.String(), nullable=True),
    sa.Column('pnd_location_id1', sa.String(), nullable=True),
    sa.Column('pnd_location_id2', sa.String(), nullable=True),
    sa.Column('last_touch', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('location_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('locations')
    # ### end Alembic commands ###
