"""Updated Orders Table

Revision ID: c8fd553f7b27
Revises: 4b9e4dfff8eb
Create Date: 2025-04-10 12:03:04.537940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8fd553f7b27'
down_revision: Union[str, None] = '4b9e4dfff8eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('label_form', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('document_form', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('order_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'order_type')
    op.drop_column('orders', 'document_form')
    op.drop_column('orders', 'label_form')
    # ### end Alembic commands ###
