"""Initial migration

Revision ID: e9f0ba14ceca
Revises: 13fdeea5e547
Create Date: 2025-03-25 12:47:17.609915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9f0ba14ceca'
down_revision: Union[str, None] = '13fdeea5e547'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=60), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('upc', sa.Float(), nullable=False),
    sa.Column('item_class', sa.String(length=50), nullable=False),
    sa.Column('is_offer', sa.Boolean(), nullable=True),
    sa.Column('default_cfg', sa.String(length=10), nullable=True),
    sa.Column('custum1', sa.String(length=30), nullable=True),
    sa.Column('custum2', sa.String(length=30), nullable=True),
    sa.Column('custum3', sa.String(length=30), nullable=True),
    sa.Column('custum4', sa.String(length=30), nullable=True),
    sa.Column('custum5', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=30), nullable=True),
    sa.Column('max_logins', sa.Float(), nullable=True),
    sa.Column('email_addr', sa.String(), nullable=True),
    sa.Column('pall_cap', sa.String(), nullable=False),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('items')
    # ### end Alembic commands ###
