"""added description colun

Revision ID: fb91fa272ec3
Revises: 143696549d71
Create Date: 2025-03-26 13:24:24.478538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb91fa272ec3'
down_revision: Union[str, None] = '143696549d71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_class', sa.Column('description', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_class', 'description')
    # ### end Alembic commands ###
