"""Updated Orders Table added more columns

Revision ID: fe6a01060dec
Revises: c8fd553f7b27
Create Date: 2025-04-10 13:44:45.374626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe6a01060dec'
down_revision: Union[str, None] = 'c8fd553f7b27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('carrier', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('ship_method', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('customer_PO', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('shp_to_Company', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('shp_to_Addres', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('shp_to_Addres2', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('shp_to_City', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('shp_to_State', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('shp_to_ZipCode', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('shp_to_Country', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('shp_to_ContactName', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('shp_to_ContactPhone', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('shp_to_TaxId', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('bill_to_Company', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('bill_to_Addres', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('bill_to_Addres2', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('bill_to_City', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('bill_to_State', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('bill_to_ZipCode', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('bill_to_Country', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('bill_to_ContactName', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('bill_to_ContactPhone', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('bill_to_TaxId', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('InvoiceNumber', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('Store', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('Vendor_num', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('custom_1', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('custom_2', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('custom_3', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('custom_4', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('custom_5', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'custom_5')
    op.drop_column('orders', 'custom_4')
    op.drop_column('orders', 'custom_3')
    op.drop_column('orders', 'custom_2')
    op.drop_column('orders', 'custom_1')
    op.drop_column('orders', 'Vendor_num')
    op.drop_column('orders', 'Store')
    op.drop_column('orders', 'InvoiceNumber')
    op.drop_column('orders', 'bill_to_TaxId')
    op.drop_column('orders', 'bill_to_ContactPhone')
    op.drop_column('orders', 'bill_to_ContactName')
    op.drop_column('orders', 'bill_to_Country')
    op.drop_column('orders', 'bill_to_ZipCode')
    op.drop_column('orders', 'bill_to_State')
    op.drop_column('orders', 'bill_to_City')
    op.drop_column('orders', 'bill_to_Addres2')
    op.drop_column('orders', 'bill_to_Addres')
    op.drop_column('orders', 'bill_to_Company')
    op.drop_column('orders', 'shp_to_TaxId')
    op.drop_column('orders', 'shp_to_ContactPhone')
    op.drop_column('orders', 'shp_to_ContactName')
    op.drop_column('orders', 'shp_to_Country')
    op.drop_column('orders', 'shp_to_ZipCode')
    op.drop_column('orders', 'shp_to_State')
    op.drop_column('orders', 'shp_to_City')
    op.drop_column('orders', 'shp_to_Addres2')
    op.drop_column('orders', 'shp_to_Addres')
    op.drop_column('orders', 'shp_to_Company')
    op.drop_column('orders', 'customer_PO')
    op.drop_column('orders', 'ship_method')
    op.drop_column('orders', 'carrier')
    # ### end Alembic commands ###
