"""Update

Revision ID: 19c35bc9c438
Revises: cf9a8d690d4d
Create Date: 2025-04-15 11:59:30.361226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19c35bc9c438'
down_revision: Union[str, None] = 'cf9a8d690d4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('purchase_order_lines', sa.Column('item_code', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_order_lines', 'item_code')
    # ### end Alembic commands ###
