"""Created table orders, receipts,vendors, PO

Revision ID: 2aabdb8a7349
Revises: f15c9a4346ba
Create Date: 2025-04-07 13:28:40.723875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aabdb8a7349'
down_revision: Union[str, None] = 'f15c9a4346ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pick_clases')
    op.drop_table('putaway_clases')
    op.drop_table('restock_clases')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restock_clases',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=50), nullable=True),
    sa.Column('class_name', sa.VARCHAR(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('putaway_clases',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=50), nullable=True),
    sa.Column('class_name', sa.VARCHAR(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pick_clases',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=50), nullable=True),
    sa.Column('class_name', sa.VARCHAR(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
