"""Create Orders table

Revision ID: 2b0c646e5fb7
Revises: 1983d9b7dc5c
Create Date: 2025-04-10 15:02:18.005291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b0c646e5fb7'
down_revision: Union[str, None] = '1983d9b7dc5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('ship_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('comments', sa.String(length=200), nullable=True),
    sa.Column('label_form', sa.String(length=50), nullable=True),
    sa.Column('document_form', sa.String(length=50), nullable=True),
    sa.Column('order_type', sa.String(length=50), nullable=True),
    sa.Column('carrier', sa.String(length=50), nullable=True),
    sa.Column('ship_method', sa.String(length=50), nullable=True),
    sa.Column('customer_PO', sa.String(length=50), nullable=True),
    sa.Column('shp_to_Company', sa.String(length=50), nullable=True),
    sa.Column('shp_to_Addres', sa.String(length=50), nullable=True),
    sa.Column('shp_to_Addres2', sa.String(length=50), nullable=True),
    sa.Column('shp_to_City', sa.String(length=50), nullable=True),
    sa.Column('shp_to_State', sa.String(length=50), nullable=True),
    sa.Column('shp_to_ZipCode', sa.String(length=50), nullable=True),
    sa.Column('shp_to_Country', sa.String(length=50), nullable=True),
    sa.Column('shp_to_ContactName', sa.String(length=50), nullable=True),
    sa.Column('shp_to_ContactPhone', sa.String(length=50), nullable=True),
    sa.Column('shp_to_TaxId', sa.String(length=50), nullable=True),
    sa.Column('bill_to_Company', sa.String(length=50), nullable=True),
    sa.Column('bill_to_Addres', sa.String(length=50), nullable=True),
    sa.Column('bill_to_Addres2', sa.String(length=50), nullable=True),
    sa.Column('bill_to_City', sa.String(length=50), nullable=True),
    sa.Column('bill_to_State', sa.String(length=50), nullable=True),
    sa.Column('bill_to_ZipCode', sa.String(length=50), nullable=True),
    sa.Column('bill_to_Country', sa.String(length=50), nullable=True),
    sa.Column('bill_to_ContactName', sa.String(length=50), nullable=True),
    sa.Column('bill_to_ContactPhone', sa.String(length=50), nullable=True),
    sa.Column('bill_to_TaxId', sa.String(length=50), nullable=True),
    sa.Column('InvoiceNumber', sa.String(length=50), nullable=True),
    sa.Column('Store', sa.String(length=50), nullable=True),
    sa.Column('Vendor_num', sa.String(length=50), nullable=True),
    sa.Column('custom_1', sa.String(length=50), nullable=True),
    sa.Column('custom_2', sa.String(length=50), nullable=True),
    sa.Column('custom_3', sa.String(length=50), nullable=True),
    sa.Column('custom_4', sa.String(length=50), nullable=True),
    sa.Column('custom_5', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
