"""created Doc from and label Form

Revision ID: 4b9e4dfff8eb
Revises: 5dc43e9d9613
Create Date: 2025-04-09 14:43:51.257037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b9e4dfff8eb'
down_revision: Union[str, None] = '5dc43e9d9613'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_form', sa.Column('action', sa.String(length=50), nullable=True))
    op.add_column('document_form', sa.Column('template_content', sa.String(), nullable=True))
    op.add_column('label_form', sa.Column('action', sa.String(length=50), nullable=True))
    op.add_column('label_form', sa.Column('template_content', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('label_form', 'template_content')
    op.drop_column('label_form', 'action')
    op.drop_column('document_form', 'template_content')
    op.drop_column('document_form', 'action')
    # ### end Alembic commands ###
