"""Initial migration

Revision ID: 5d7a82f9615c
Revises: 
Create Date: 2025-04-02 18:47:27.039080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d7a82f9615c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_class',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_class_id', sa.String(), nullable=False),
    sa.Column('description', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=60), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('upc', sa.Integer(), nullable=False),
    sa.Column('alt_item_id1', sa.Integer(), nullable=True),
    sa.Column('alt_item_id2', sa.Integer(), nullable=True),
    sa.Column('item_class', sa.String(length=50), nullable=True),
    sa.Column('description2', sa.String(length=50), nullable=True),
    sa.Column('is_offer', sa.Boolean(), nullable=True),
    sa.Column('default_cfg', sa.String(length=10), nullable=True),
    sa.Column('brand', sa.String(length=30), nullable=True),
    sa.Column('style', sa.String(length=30), nullable=True),
    sa.Column('custum1', sa.String(length=30), nullable=True),
    sa.Column('custum2', sa.String(length=30), nullable=True),
    sa.Column('custum3', sa.String(length=30), nullable=True),
    sa.Column('custum4', sa.String(length=30), nullable=True),
    sa.Column('custum5', sa.String(length=30), nullable=True),
    sa.Column('custum6', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location_type',
    sa.Column('location_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('system_flag', sa.String(length=1), nullable=True),
    sa.Column('sto_pall_flag', sa.String(length=1), nullable=True),
    sa.Column('sto_pall_cart_flag', sa.String(length=1), nullable=True),
    sa.Column('sto_pall_con_flag', sa.String(length=1), nullable=True),
    sa.Column('sto_cart_flag', sa.String(length=1), nullable=True),
    sa.Column('sto_cont_flag', sa.String(length=1), nullable=True),
    sa.Column('mix_item_flag', sa.String(length=1), nullable=True),
    sa.Column('mix_cfg_flag', sa.String(length=1), nullable=True),
    sa.Column('mix_trackingdate_flag', sa.String(length=1), nullable=True),
    sa.Column('mix_receivingdate_flag', sa.String(length=1), nullable=True),
    sa.Column('mix_recdate_flag', sa.String(length=1), nullable=True),
    sa.Column('merge_flag', sa.String(length=1), nullable=True),
    sa.Column('trash_pall', sa.String(length=1), nullable=True),
    sa.Column('merge_cfg_code', sa.String(length=1), nullable=True),
    sa.Column('merge_trackingdate', sa.String(length=1), nullable=True),
    sa.Column('merge_inventory_type', sa.String(length=1), nullable=True),
    sa.Column('merge_receiving_date', sa.String(length=1), nullable=True),
    sa.Column('pick_pallet_flag', sa.String(length=1), nullable=True),
    sa.Column('pick_cart_flag', sa.String(length=1), nullable=True),
    sa.Column('pick_piece_flag', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('location_type')
    )
    op.create_table('locations',
    sa.Column('location_id', sa.String(), nullable=False),
    sa.Column('location_type', sa.String(), nullable=False),
    sa.Column('scan_location', sa.String(), nullable=True),
    sa.Column('black_hole_flag', sa.String(length=1), nullable=True),
    sa.Column('proximiti_in', sa.String(), nullable=True),
    sa.Column('proximiti_out', sa.String(), nullable=True),
    sa.Column('has_assign_flag', sa.String(length=1), nullable=True),
    sa.Column('has_contents_flag', sa.String(length=1), nullable=True),
    sa.Column('has_pending_flag', sa.String(length=1), nullable=True),
    sa.Column('putaway_class', sa.String(), nullable=True),
    sa.Column('pick_class', sa.String(), nullable=True),
    sa.Column('rstk_class', sa.String(), nullable=True),
    sa.Column('blocked_code', sa.String(), nullable=True),
    sa.Column('palle_cap', sa.Integer(), nullable=True),
    sa.Column('carton_cap', sa.Integer(), nullable=True),
    sa.Column('max_weight', sa.Float(), nullable=True),
    sa.Column('max_height', sa.Float(), nullable=True),
    sa.Column('max_width', sa.Float(), nullable=True),
    sa.Column('max_depth', sa.Float(), nullable=True),
    sa.Column('uom_max_weight', sa.String(), nullable=True),
    sa.Column('uom_max_height', sa.String(), nullable=True),
    sa.Column('uom_max_width', sa.String(), nullable=True),
    sa.Column('uom_max_depth', sa.String(), nullable=True),
    sa.Column('uom_carton_cap', sa.String(), nullable=True),
    sa.Column('pallet_qty_act', sa.Integer(), nullable=True),
    sa.Column('carton_qty_act', sa.Integer(), nullable=True),
    sa.Column('aisle', sa.String(), nullable=True),
    sa.Column('bay', sa.String(), nullable=True),
    sa.Column('loc_level', sa.String(), nullable=True),
    sa.Column('slot', sa.String(), nullable=True),
    sa.Column('pnd_location_id1', sa.String(), nullable=True),
    sa.Column('pnd_location_id2', sa.String(), nullable=True),
    sa.Column('last_touch', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_table('pick_clases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('class', sa.String(length=15), nullable=True),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('putaway_clases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('class', sa.String(length=15), nullable=True),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restock_clases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('class', sa.String(length=15), nullable=True),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=30), nullable=True),
    sa.Column('max_logins', sa.Integer(), nullable=False),
    sa.Column('email_addr', sa.String(), nullable=True),
    sa.Column('pall_cap', sa.Integer(), nullable=False),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('restock_clases')
    op.drop_table('putaway_clases')
    op.drop_table('pick_clases')
    op.drop_table('locations')
    op.drop_table('location_type')
    op.drop_table('items')
    op.drop_table('item_class')
    # ### end Alembic commands ###
