"""added tables cycle_codes and block_codes

Revision ID: 9c16a7a045e1
Revises: e15ebbaee16f
Create Date: 2025-04-02 18:54:46.450531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c16a7a045e1'
down_revision: Union[str, None] = 'e15ebbaee16f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proximities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proximity', sa.String(length=10), nullable=False),
    sa.Column('movers', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proximities')
    # ### end Alembic commands ###
