"""Updated Receipts table

Revision ID: b2fc9d9c6558
Revises: 8a5a74572bbd
Create Date: 2025-04-11 13:00:29.207616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2fc9d9c6558'
down_revision: Union[str, None] = '8a5a74572bbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('vendor_name', sa.String(length=100), nullable=True))
    op.add_column('receipts', sa.Column('release_num', sa.String(length=50), nullable=True))
    op.add_column('receipts', sa.Column('invoice_num', sa.String(length=50), nullable=True))
    op.add_column('receipts', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('receipts', sa.Column('date_shipped', sa.DateTime(), nullable=True))
    op.add_column('receipts', sa.Column('date_expected', sa.DateTime(), nullable=True))
    op.add_column('receipts', sa.Column('date_received', sa.DateTime(), nullable=True))
    op.add_column('receipts', sa.Column('label_form', sa.String(length=50), nullable=True))
    op.add_column('receipts', sa.Column('document_form', sa.String(length=50), nullable=True))
    op.add_column('receipts', sa.Column('close_receipt', sa.Boolean(), nullable=True))
    op.add_column('receipts', sa.Column('carrier', sa.String(length=100), nullable=True))
    op.add_column('receipts', sa.Column('seal_num', sa.String(length=50), nullable=True))
    op.add_column('receipts', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('receipts', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('receipts', sa.Column('ship_from_company', sa.String(length=100), nullable=True))
    op.add_column('receipts', sa.Column('ship_from_address', sa.String(length=150), nullable=True))
    op.add_column('receipts', sa.Column('ship_from_address2', sa.String(length=150), nullable=True))
    op.add_column('receipts', sa.Column('ship_from_city', sa.String(length=50), nullable=True))
    op.add_column('receipts', sa.Column('ship_from_state', sa.String(length=50), nullable=True))
    op.add_column('receipts', sa.Column('ship_from_zip', sa.String(length=20), nullable=True))
    op.add_column('receipts', sa.Column('ship_from_country', sa.String(length=50), nullable=True))
    op.add_column('receipts', sa.Column('ship_from_contact_name', sa.String(length=100), nullable=True))
    op.add_column('receipts', sa.Column('ship_from_contact_phone', sa.String(length=30), nullable=True))
    op.add_column('receipts', sa.Column('ship_from_tax_id', sa.String(length=30), nullable=True))
    op.add_column('receipts', sa.Column('bill_to_company', sa.String(length=100), nullable=True))
    op.add_column('receipts', sa.Column('bill_to_address', sa.String(length=150), nullable=True))
    op.add_column('receipts', sa.Column('bill_to_address2', sa.String(length=150), nullable=True))
    op.add_column('receipts', sa.Column('bill_to_city', sa.String(length=50), nullable=True))
    op.add_column('receipts', sa.Column('bill_to_state', sa.String(length=50), nullable=True))
    op.add_column('receipts', sa.Column('bill_to_zip', sa.String(length=20), nullable=True))
    op.add_column('receipts', sa.Column('bill_to_country', sa.String(length=50), nullable=True))
    op.add_column('receipts', sa.Column('bill_to_contact_name', sa.String(length=100), nullable=True))
    op.add_column('receipts', sa.Column('bill_to_contact_phone', sa.String(length=30), nullable=True))
    op.add_column('receipts', sa.Column('bill_to_tax_id', sa.String(length=30), nullable=True))
    op.add_column('receipts', sa.Column('custom_1', sa.String(length=100), nullable=True))
    op.add_column('receipts', sa.Column('custom_2', sa.String(length=100), nullable=True))
    op.add_column('receipts', sa.Column('custom_3', sa.String(length=100), nullable=True))
    op.add_column('receipts', sa.Column('custom_4', sa.String(length=100), nullable=True))
    op.add_column('receipts', sa.Column('custom_5', sa.String(length=100), nullable=True))
    op.add_column('receipts', sa.Column('custom_6', sa.String(length=100), nullable=True))
    op.add_column('receipts', sa.Column('custom_7', sa.String(length=100), nullable=True))
    op.add_column('receipts', sa.Column('custom_8', sa.String(length=100), nullable=True))
    op.add_column('receipts', sa.Column('custom_9', sa.String(length=100), nullable=True))
    op.add_column('receipts', sa.Column('custom_10', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipts', 'custom_10')
    op.drop_column('receipts', 'custom_9')
    op.drop_column('receipts', 'custom_8')
    op.drop_column('receipts', 'custom_7')
    op.drop_column('receipts', 'custom_6')
    op.drop_column('receipts', 'custom_5')
    op.drop_column('receipts', 'custom_4')
    op.drop_column('receipts', 'custom_3')
    op.drop_column('receipts', 'custom_2')
    op.drop_column('receipts', 'custom_1')
    op.drop_column('receipts', 'bill_to_tax_id')
    op.drop_column('receipts', 'bill_to_contact_phone')
    op.drop_column('receipts', 'bill_to_contact_name')
    op.drop_column('receipts', 'bill_to_country')
    op.drop_column('receipts', 'bill_to_zip')
    op.drop_column('receipts', 'bill_to_state')
    op.drop_column('receipts', 'bill_to_city')
    op.drop_column('receipts', 'bill_to_address2')
    op.drop_column('receipts', 'bill_to_address')
    op.drop_column('receipts', 'bill_to_company')
    op.drop_column('receipts', 'ship_from_tax_id')
    op.drop_column('receipts', 'ship_from_contact_phone')
    op.drop_column('receipts', 'ship_from_contact_name')
    op.drop_column('receipts', 'ship_from_country')
    op.drop_column('receipts', 'ship_from_zip')
    op.drop_column('receipts', 'ship_from_state')
    op.drop_column('receipts', 'ship_from_city')
    op.drop_column('receipts', 'ship_from_address2')
    op.drop_column('receipts', 'ship_from_address')
    op.drop_column('receipts', 'ship_from_company')
    op.drop_column('receipts', 'created_date')
    op.drop_column('receipts', 'created_by')
    op.drop_column('receipts', 'seal_num')
    op.drop_column('receipts', 'carrier')
    op.drop_column('receipts', 'close_receipt')
    op.drop_column('receipts', 'document_form')
    op.drop_column('receipts', 'label_form')
    op.drop_column('receipts', 'date_received')
    op.drop_column('receipts', 'date_expected')
    op.drop_column('receipts', 'date_shipped')
    op.drop_column('receipts', 'status')
    op.drop_column('receipts', 'invoice_num')
    op.drop_column('receipts', 'release_num')
    op.drop_column('receipts', 'vendor_name')
    # ### end Alembic commands ###
