"""Update purchase_order_lines V3

Revision ID: cf9a8d690d4d
Revises: a48e8da24d87
Create Date: 2025-04-14 17:20:47.670372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf9a8d690d4d'
down_revision: Union[str, None] = 'a48e8da24d87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_order_lines', sa.Column('line_number', sa.Integer(), nullable=False))
    op.add_column('purchase_order_lines', sa.Column('upc', sa.String(length=50), nullable=True))
    op.add_column('purchase_order_lines', sa.Column('description', sa.String(length=100), nullable=True))
    op.add_column('purchase_order_lines', sa.Column('qty_expected', sa.Integer(), nullable=False))
    op.add_column('purchase_order_lines', sa.Column('uom', sa.String(length=20), nullable=True))
    op.add_column('purchase_order_lines', sa.Column('lot_number', sa.String(length=50), nullable=True))
    op.add_column('purchase_order_lines', sa.Column('expiration_date', sa.Date(), nullable=True))
    op.add_column('purchase_order_lines', sa.Column('location_received', sa.String(length=50), nullable=True))
    op.add_column('purchase_order_lines', sa.Column('custom_1', sa.String(length=100), nullable=True))
    op.add_column('purchase_order_lines', sa.Column('custom_2', sa.String(length=100), nullable=True))
    op.add_column('purchase_order_lines', sa.Column('custom_3', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_order_lines', 'custom_3')
    op.drop_column('purchase_order_lines', 'custom_2')
    op.drop_column('purchase_order_lines', 'custom_1')
    op.drop_column('purchase_order_lines', 'location_received')
    op.drop_column('purchase_order_lines', 'expiration_date')
    op.drop_column('purchase_order_lines', 'lot_number')
    op.drop_column('purchase_order_lines', 'uom')
    op.drop_column('purchase_order_lines', 'qty_expected')
    op.drop_column('purchase_order_lines', 'description')
    op.drop_column('purchase_order_lines', 'upc')
    op.drop_column('purchase_order_lines', 'line_number')
    op.alter_column('a_contents', 'item_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
