"""added tables cycle_codes and block_codes

Revision ID: f15c9a4346ba
Revises: 9c16a7a045e1
Create Date: 2025-04-02 19:25:11.762080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f15c9a4346ba'
down_revision: Union[str, None] = '9c16a7a045e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pick_clases', sa.Column('class_name', sa.String(length=15), nullable=True))
    op.drop_column('pick_clases', 'class')
    op.add_column('putaway_clases', sa.Column('class_name', sa.String(length=15), nullable=True))
    op.drop_column('putaway_clases', 'class')
    op.add_column('restock_clases', sa.Column('class_name', sa.String(length=15), nullable=True))
    op.drop_column('restock_clases', 'class')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restock_clases', sa.Column('class', sa.VARCHAR(length=15), nullable=True))
    op.drop_column('restock_clases', 'class_name')
    op.add_column('putaway_clases', sa.Column('class', sa.VARCHAR(length=15), nullable=True))
    op.drop_column('putaway_clases', 'class_name')
    op.add_column('pick_clases', sa.Column('class', sa.VARCHAR(length=15), nullable=True))
    op.drop_column('pick_clases', 'class_name')
    # ### end Alembic commands ###
