# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/proximities.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(402, 631)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidgetProximities = QtWidgets.QTableWidget(Form)
        self.tableWidgetProximities.setObjectName("tableWidgetProximities")
        self.tableWidgetProximities.setColumnCount(0)
        self.tableWidgetProximities.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidgetProximities, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Proximities"))
