# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/Forms.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Forms(object):
    def setupUi(self, Forms):
        Forms.setObjectName("Forms")
        Forms.resize(624, 476)
        self.gridLayout_2 = QtWidgets.QGridLayout(Forms)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(Forms)
        self.tabWidget.setObjectName("tabWidget")
        self.DocForm = QtWidgets.QWidget()
        self.DocForm.setObjectName("DocForm")
        self.gridLayout = QtWidgets.QGridLayout(self.DocForm)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidgetDocForms = QtWidgets.QTableWidget(self.DocForm)
        self.tableWidgetDocForms.setObjectName("tableWidgetDocForms")
        self.tableWidgetDocForms.setColumnCount(0)
        self.tableWidgetDocForms.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidgetDocForms, 0, 0, 1, 1)
        self.tabWidget.addTab(self.DocForm, "")
        self.LabelForm = QtWidgets.QWidget()
        self.LabelForm.setObjectName("LabelForm")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.LabelForm)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tableWidget_LabelForms = QtWidgets.QTableWidget(self.LabelForm)
        self.tableWidget_LabelForms.setObjectName("tableWidget_LabelForms")
        self.tableWidget_LabelForms.setColumnCount(0)
        self.tableWidget_LabelForms.setRowCount(0)
        self.gridLayout_3.addWidget(self.tableWidget_LabelForms, 0, 0, 1, 1)
        self.tabWidget.addTab(self.LabelForm, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Forms)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Forms)

    def retranslateUi(self, Forms):
        _translate = QtCore.QCoreApplication.translate
        Forms.setWindowTitle(_translate("Forms", "Form"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.DocForm), _translate("Forms", "Document Forms"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.LabelForm), _translate("Forms", "Label Forms"))
