# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/order_Types.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OrderTypes(object):
    def setupUi(self, OrderTypes):
        OrderTypes.setObjectName("OrderTypes")
        OrderTypes.resize(641, 547)
        self.gridLayout = QtWidgets.QGridLayout(OrderTypes)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidgetOrderTypes = QtWidgets.QTableWidget(OrderTypes)
        self.tableWidgetOrderTypes.setObjectName("tableWidgetOrderTypes")
        self.tableWidgetOrderTypes.setColumnCount(0)
        self.tableWidgetOrderTypes.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidgetOrderTypes, 0, 0, 1, 1)

        self.retranslateUi(OrderTypes)
        QtCore.QMetaObject.connectSlotsByName(OrderTypes)

    def retranslateUi(self, OrderTypes):
        _translate = QtCore.QCoreApplication.translate
        OrderTypes.setWindowTitle(_translate("OrderTypes", "Order Types"))
